name: GemApi
version: VERSION
main: me.mickyjou.plugins.gems.api.GemApi
author: Mickyjou
commands:
     gems:
          description: Gem commands
          usage: /gems (add|remove|set) [player] <amount>
